name: US-miner3
on:
  schedule:
    - cron: '*/120 * * * *'  # Fixed cron syntax (added missing asterisks)
  workflow_dispatch:

concurrency:
  group: us-group3
  cancel-in-progress: true

jobs:
  check-proxies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure full history is fetched to prevent non-fast-forward issues
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
    
    - name: Install dependencies
      run: npm install
    
    - name: Check proxies
      run: |
        npm run us